[book]
authors = ["Srevin Saju"]
language = "en"
multilingual = false
src = "src"
title = "togomak"

[output.html]
additional-js = ["js/terraform.js", "js/init.js"]


[output.html.code.hidelines]
hcl = "~"
