name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Build
        run: go build -o ./togomak ./cmd/togomak/.
      - name: Coverage 
        run: ./togomak -C tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          functionalities: search
